export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const RECEIVE_CHANNEL = 'RECEIVE_CHANNEL';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const TYPING = 'TYPING';
export const STOP_TYPING = 'STOP_TYPING';

export const ADD_USER = 'ADD_USER';

export const REMOVE_USER_FROM_CHANNEL = 'REMOVE_USER_FROM_CHANNEL';

export const SAVE_USERNAME = 'SAVE_USERNAME';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';

export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const LOAD_CHANNELS_SUCCESS  = 'LOAD_CHANNELS_SUCCESS';
export const LOAD_CHANNELS_FAIL = 'LOAD_CHANNELS_FAIL';

export const LOAD_USERSONLINE = 'LOAD_USERSONLINE';
export const LOAD_USERSONLINE_SUCCESS = 'LOAD_USERSONLINE_SUCCESS';
export const LOAD_USERSONLINE_FAIL = 'LOAD_USERSONLINE_FAIL';

export const RECEIVE_USER = 'RECEIVE_USER';

export const START_USERNAME_VALIDATION = 'START_USERNAME_VALIDATION';
export const USERNAME_VALIDATION_SUCCESS = 'USERNAME_VALIDATION_SUCCESS';
export const USERNAME_VALIDATION_FAIL = 'USERNAME_VALIDATION_FAIL';

export const LOAD_USERVALIDATION = 'LOAD_USERVALIDATION';
export const LOAD_USERVALIDATION_SUCCESS = 'LOAD_USERVALIDATION_SUCCESS';
export const LOAD_USERVALIDATION_FAIL = 'LOAD_USERVALIDATION_FAIL';

export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

export const RECEIVE_SOCKET = 'RECEIVE_SOCKET';

